<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Extension\ExtensionPathResolver;

/**
 * Implements hook_preprocess_node().
 */
function swislr_stories_preprocess_node(array &$variables) {
  $node = $variables['node'] ?? NULL;
  if ($node instanceof NodeInterface && $node->bundle() === 'story') {
    // Attach Story-only styles.
    $variables['#attached']['library'][] = 'swislr_stories/story-node';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function swislr_stories_theme_registry_alter(array &$theme_registry) {
  /** @var \Drupal\Core\Extension\ExtensionPathResolver $resolver */
  $resolver = \Drupal::service('extension.path.resolver');
  $module_path = $resolver->getPath('module', 'swislr_stories') . '/templates';

  // Generic Story override.
  if (isset($theme_registry['node__story'])) {
    $theme_registry['node__story']['path'] = $module_path;
  }
  // Full view mode override.
  if (isset($theme_registry['node__story__full'])) {
    $theme_registry['node__story__full']['path'] = $module_path;
  }
}

