services:
  drupal:
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
      - ./modules/custom:/var/www/html/modules/custom
      - ./themes/custom:/var/www/html/themes/custom
