version: '3.8'

services:
  drupal:
    # Build your site image in Dockerfile (FROM drupal:10-apache … copy code in)
    image: yourrepo/drupal-app:latest
    ports:
      - "8080:80"
    volumes:
      - drupal-files:/var/www/html/sites/default/files
      - drupal-private:/var/www/private
      - ./docker/php/zz-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini:ro
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - drupal-db:/var/lib/mysql
    restart: unless-stopped

volumes:
  drupal-files:
  drupal-private:
  drupal-db:

