<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view_alter().
 */

function swislr_attach_theme_css_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'story') {
    $build['#attached']['library'][] = 'swislr_attach_theme_css/story';
  }
}

