<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view_alter().
 */
function swislr_attach_theme_css_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'story') {
    // Attach your library here.
    $build['#attached']['library'][] = 'swislr_story_styling/custom-overrides';
  }
}

