<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view_alter().
 */

function swislr_attach_theme_css_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() === 'node') {
    $bundle = $entity->bundle();
    if ($bundle === 'story') {
      $build['#attached']['library'][] = 'swislr_attach_theme_css/story';
    }
    elseif ($bundle === 'dataset') {
      $build['#attached']['library'][] = 'swislr_attach_theme_css/dataset';
    }
    elseif ($bundle === 'discussion') {
      $build['#attached']['library'][] = 'swislr_attach_theme_css/forum';
    }
  }
}

